[package]
name = "rtuner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "^0"
wav = "^1"
pitch-detection = "^0.3"
tui = "0.19.0"
crossterm = "0.25.0"

[profile.release]
lto = true
